### ISSUE TITLE
Tablet survey does not intercept clicks

### ISSUE THREAD

**Issue by jahunt1** [Wootric/WootricSDK-Android#39]
## Version info
  - Wootric Android SDK version: 2.4.10
  - Android OS version: 7.0 Nougat
  - Android Device: Nexus 7 Emulator

## Expected behavior
Tapping within the area of the screen covered by the survey should not interact with the Views behind the survey.

## Actual behavior
Any tap outside of the wootric_et_feedback EditText or the ScoreView 0-10 views sends the click through to the View behind it. This is inconvenient because if the user misses their target even by a tiny amount, the UI will unexpectedly change.

## Steps to reproduce
 1. Build a layout with clickable Views that would be covered by the survey on a tablet.
 2. Click near, but just outside the EditText.
 3. Observe that the View behind the survey responds to the click event.

**Comment by diegoserranoa** [comment]
@jahunt1 thanks for reporting this. We'll take a look asap.

**Comment by diegoserranoa** [comment]
This issue was resolved on PR #40
