### ISSUE TITLE
Add ability to change input text color

### ISSUE THREAD

**Issue by piotrmadry** [Wootric/WootricSDK-Android#52]
Hello!
I've faced problem with input text color when I've tried to type something.
![main](https://user-images.githubusercontent.com/20104842/32323064-fcf48406-bfc6-11e7-8242-2b22e992eea6.png)

Can you please add ability to control this color ? 

Thanks!
Piotr

**Comment by prabhatjha** [comment]
HI @piotrmadry We had this problem with our older version of SDK but we fixed it and our other customers verified that fix worked for them. Would you pls let us know which version you are using?

Thanks.

**Comment by diegoserranoa** [comment]
Hi @piotrmadry we verified that you guys are using SDK version `2.4.7`. This was fixed in version (2.5.1)[https://github.com/Wootric/WootricSDK-Android/blob/master/CHANGELOG.md#251-2017-05-26]. If this is still happening with newer versions please let us know and we'll reopen this issue!
