### ISSUE TITLE
Show error message when WootricRemoteRequestTask fails

### ISSUE THREAD

**Issue by regmoraes** [Wootric/WootricSDK-Android#55]
When executing the WootricRemoteRequestTask, if the request fails, the log only shows `response: null`

<img width="551" alt="screen shot 2018-02-28 at 11 31 45" src="https://user-images.githubusercontent.com/4440882/36793032-07058d1c-1c7b-11e8-8270-f11e4feaf8db.png">

It would be great if the actual error message was show

**A simple solution would be to add a `Log.d` on the `catch` block**
    
```
@Override
protected String doInBackground(Void... params) {

    try { 
         /*...*/        

    } catch (IOException e) {
         Log.d("WOOTRIC_SDK", "request failed because of: " + e.getMessage()); 
         onError(e);
    }
        return null;
    }
```

**Comment by diegoserranoa** [comment]
Added this in the latest release https://github.com/Wootric/WootricSDK-Android/releases/tag/2.17.0
Closing this issue. Thanks!
