### ISSUE TITLE
Can't set text color for texts next to social icons

### ISSUE THREAD

**Issue by soniccat** [Wootric/WootricSDK-Android#60]
Hello, I'm trying to enable social icons on a "Thank you" page on Android (2.8.0 version). And it seems I've found a bug. When I call setSocialSharingColor it works only for icons but not for texts next to them. Looking at your source code I see you have TextViews wootric_tv_facebook_like, wootric_tv_facebook, wootric_tv_twitter but don't call setTextColor for them at all in ThankYouLayout.java.

I've attached 2 screens to show that mCurTextColor values are different for the icon and the text

<img width="999" alt="2018-07-23 15 34 01" src="https://user-images.githubusercontent.com/147129/43078171-5d653458-8e92-11e8-9691-6f66df562869.png">
<img width="1000" alt="2018-07-23 15 33 53" src="https://user-images.githubusercontent.com/147129/43078173-5ed1bbfe-8e92-11e8-8bbc-50c1bf3ec3ec.png">

**Comment by m4rtint** [comment]
pinging @diegoserranoa just incase you don't see this.

**Comment by diegoserranoa** [comment]
Hi guys, I'm closing this issue since we believe this has been fixed in the latest releases and it's already 2 years old.

If your still having this issue, please contact us and we'll look over it again.

Thanks!
