### ISSUE TITLE
Text on buttons is invisible on tablets

### ISSUE THREAD

**Issue by soniccat** [Wootric/WootricSDK-Android#62]
I see you don't update text color in ScoreView on creation. You do that only in onClick. That's why text is invisible.

![screenshot_1532520652](https://user-images.githubusercontent.com/147129/43322285-c006d32e-91b6-11e8-9a7d-b3e9e446a8cf.png)

![screenshot_1532695990](https://user-images.githubusercontent.com/147129/43322260-b3cbb98a-91b6-11e8-81a4-e631ef0d1a1d.png)

**Comment by m4rtint** [comment]
pinging @diegoserranoa just incase you don't see this.

**Comment by diegoserranoa** [comment]
Hi guys, sorry for the looong delay. I've been juggling through other stuff. I believe this was fixed in the more recent versions of the SDK so I will close this issue. If you're still having this issue with the new version, please reach out to us again.

Thanks for understanding 🙏
