### ISSUE TITLE
Return button doesn't move to the next page

### ISSUE THREAD

**Issue by soniccat** [Wootric/WootricSDK-Android#63]
It would be great to be able to change the default behaviour of the "Enter" keyboard button. Now it adds a new line to a feedback. Instead we would like to open the next review page.

![screenshot_1532967854](https://user-images.githubusercontent.com/147129/43411003-88ab9aea-9431-11e8-8fa2-61c6a33e3674.png)

![screenshot_1532967856](https://user-images.githubusercontent.com/147129/43411001-876fcef8-9431-11e8-8429-0b5be8ea7f6e.png)

**Comment by diegoserranoa** [comment]
Hello again @soniccat , we're taking care of this and should be out in the next release of the SDK. I'll reference this issue once the PR is out.

**Comment by diegoserranoa** [comment]
Added this in the latest release https://github.com/Wootric/WootricSDK-Android/releases/tag/2.17.0
Closing this issue. Thanks!
