### ISSUE TITLE
UI glitch in the slider

### ISSUE THREAD

**Issue by soniccat** [Wootric/WootricSDK-Android#64]
We found that the number 10 might not fit

![screenshot_2018-07-30-11-17-24](https://user-images.githubusercontent.com/147129/43456676-15b955c6-94cd-11e8-9c9b-9a21f53a0eea.png)

**Comment by diegoserranoa** [comment]
Hi @soniccat, again sorry for the long delay. Wasn't able to replicate this with the latest version. Are you still having this issue?

**Comment by diegoserranoa** [comment]
Hi @soniccat, I'm closing this issue also since we believe this has been fixed in the latest versions. If you're still having this issue, please contact us know and we'll look over it.

Thanks!
