### ISSUE TITLE
Input is invisible in a narrow device

### ISSUE THREAD

**Issue by soniccat** [Wootric/WootricSDK-Android#65]
I can't see an input field in a narrow device:

![screenshot_2018-07-30-11-46-33](https://user-images.githubusercontent.com/147129/43457337-359c8c62-94cf-11e8-8f56-ea708bd127a8.png)

**Comment by diegoserranoa** [comment]
Hi @soniccat, same as the other issues, if you're still having this problem let us know and we'll look over it.

Thanks 🙏
