### ISSUE TITLE
Custom colours don't and wordings are not used sometimes

### ISSUE THREAD

**Issue by soniccat** [Wootric/WootricSDK-Android#66]
Our testers saw that custom colours and wordings are not used sometimes:

![screenshot_2018-07-30-12-43-34](https://user-images.githubusercontent.com/147129/43457371-501214ea-94cf-11e8-9c84-d9badc2b8713.png)

**Comment by diegoserranoa** [comment]
Hello again @soniccat are you still having this issue? Can you provide more information?

**Comment by diegoserranoa** [comment]
Hi @soniccat same here as with other issues. If you're still having problems let me know. Thanks!
