### ISSUE TITLE
Set custom question text

### ISSUE THREAD

**Issue by alvaromb** [Wootric/WootricSDK-Android#72]
This is more a question than a bug report. Is it possible to set a custom question text in the source code? It can be done on iOS, but I can't find the way to do it on Android.

**Comment by diegoserranoa** [comment]
What do you mean by a custom question text? Modify the audience?

**Comment by alvaromb** [comment]
I mean the equivalent to iOS' `[Wootric setCustomNPSQuestion:<NPS_QUESTION>];` (that's the docs name of the method, but it's actually `setCustomQuestion`.

**Comment by diegoserranoa** [comment]
Hi @alvaromb sorry for the loooong delay in my reply. We've been juggling through other features and issues. We decided not to add this to the SDK and will be removing it from the iOS SDK.

Thanks for the comprehension.
