### ISSUE TITLE
Survey not show: WOOTRIC_SDK: API error

### ISSUE THREAD

**Issue by nguyendat** [Wootric/WootricSDK-Android#77]
I just got error when try to display survey:

`10-12 23:15:53.069 32562  1667 E WOOTRIC_SDK: API error: java.io.FileNotFoundException: https://api.wootric.com/v1/end_users?email=nps%40example.com&os_name=Android&os_version=8.0.0&sdk_version=android-2.13.0
10-12 23:15:53.073 32562 32562 D WOOTRIC_SDK: response: null`

I tested with version 2.13.0, It work fine about 5 hours ago but suddenly it not display survey anymore. I notice there are abnormal log related to API error that may related to this error.

Please let me know if you need more information.

**Comment by nguyendat** [comment]
Issue close, It work again, It seem issue have been fixed from API side. Thanks

`10-13 08:41:01.775 29343 30054 D WOOTRIC_SDK: request: https://api.wootric.com/v1/end_users?email=nps%40example.com&os_name=Android&os_version=6.0.1&sdk_version=android-2.13.0
10-13 08:41:02.303 29343 29343 D WOOTRIC_SDK: response: [{"id":198118636,"created_at":"2019-10-11 01:56:32 -0700","updated_at":"2019-10-12 00:39:09 -0700","email":"nps@example.com","last_surveyed":"2019-10-12 00:39:09 -0700","external_created_at":1234567890,"last_seen_at":null,"properties":{},"phone_number":null,"external_id":null,"last_response":{"id":40011533,"score":10,"text":null,"survey":{"channel":"mobile"}},"settings":{"email_nps":true,"mobile_nps":true,"web_nps":true,"surveys_disabled_by_end_user":null}}]`

**Comment by prabhatjha** [comment]
Hi @nguyendat I am glad it's working again. We had some infra hiccup yesterday. Looking at logs I would recommend to hange `email`, `created_at` parameter of user with value that's specific to user who logged in. The place holder value like `nps@exampl.ecom` is just to show how it is supposed to work.
