### ISSUE TITLE
Crash when using WootricCustomThankYou in 2.14.0

### ISSUE THREAD

**Issue by Gerlac** [Wootric/WootricSDK-Android#79]
In https://github.com/Wootric/WootricSDK-Android/commit/e7307fe9c7e0b6b5f0ccaeded4ab508de6139361 a change was made in WootricCustomThankYou `scoreInUrl` and `commentInUrl` to make them `Boolean` instead of `boolean`. This change makes our app crash when wootric uses writeToParcel as those properties can now be null. (We don't have a value defined for those properties)

Stacktrace:
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
com.wootric.androidsdk.objects.WootricCustomThankYou.writeToParcel (WootricCustomThankYou.java:328)

The crash can be reproduced creating a new WootricCustomThankYou without defining a specific `scoreInUrl` value. Trying to leave the app when the survey is showing up causes a crash.

**Comment by diegoserranoa** [comment]
Hi @Gerlac thanks for reporting this. We'll replicate the issue and publish a fix ASAP!

**Comment by diegoserranoa** [comment]
Hi @Gerlac we've release a new version with the fix (2.14.1). Please let us know that everything is working correctly.

**Comment by Gerlac** [comment]
Hi @diegoserranoa that's great news. We will try in our next release. Thanks for the update!
