### ISSUE TITLE
NullpointerException when invoking showSurveyFragment

### ISSUE THREAD

**Issue by nelljohan** [Wootric/WootricSDK-Android#84]
## Summary
After updating to the latest Wootric SDK we are experiencing a NullPointerException at `SurveyManager#showSurveyFragment`.

## SDK Version
2.15.0

## Stacktrace
```
E/WOOTRIC_SDK: showSurveyFragment: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.FragmentManager android.app.Activity.getFragmentManager()' on a null object reference
W/System.err:     at com.wootric.androidsdk.SurveyManager.showSurveyFragment(SurveyManager.java:306)
W/System.err:     at com.wootric.androidsdk.SurveyManager.access$000(SurveyManager.java:58)
W/System.err:     at com.wootric.androidsdk.SurveyManager$1.run(SurveyManager.java:274)
```
## Detail
From debugging the code it seems that there is a line missing after this point to initialise the `fragmentActivity` and extract a value from the `WootricEvent` 👇   https://github.com/Wootric/WootricSDK-Android/blob/285813f49aa1c83134112a4b45a146458f568b79/androidsdk/src/main/java/com/wootric/androidsdk/SurveyManager.java#L285

I can confirm that with our implementation `fragmentActivity` is populated correctly on the `WootricEvent` instead of `activity` and from reading the code it looks like the first if statement  at https://github.com/Wootric/WootricSDK-Android/blob/285813f49aa1c83134112a4b45a146458f568b79/androidsdk/src/main/java/com/wootric/androidsdk/SurveyManager.java#L287 would always evaluate to `false` even though we are expecting that value to be populated and the statement to evaluate to `true`

## Next steps
Seeing that this is currently crashing 2.15.0 for us we have rolled back to a previous release for now.

**Comment by diegoserranoa** [comment]
Hi @nelljohan,

Thanks for reporting this. We will start working on the fix and rollout a new version. I'll update this issue once it's done.

**Comment by diegoserranoa** [comment]
Hi @nelljohan,

Quick question: are you using Wootric with a `FragmentActivity` or an `Activity`?

**Comment by nelljohan** [comment]
Thanks! We are using `FragmentActivity` downstream from `DaggerAppCompatActivity` 👍

**Comment by diegoserranoa** [comment]
Thanks for the info! @nelljohan we're working on this so wanted to be sure a test this thoroughly.

**Comment by diegoserranoa** [comment]
Hi @nelljohan I've created a PR with code that hopefully fixes this issue. Would you mind giving it a try? 🙏 
https://github.com/Wootric/WootricSDK-Android/pull/85

**Comment by nelljohan** [comment]
Thanks @diegoserranoa, tested the PR on our latest build and it is working as expected 🎉 🚀
