### ISSUE TITLE
Wootric popup is not scrollable in landscape mode and user has no option to select opt out

### ISSUE THREAD

**Issue by prasannarupan** [Wootric/WootricSDK-Android#86]
The user is not able to tap on opt out button when viewing the survey pop up in landscape mode. This is due to the fact that the wootric survey pop up is not scroll able in landscape mode.

**Comment by diegoserranoa** [comment]
Hi @prasannarupan my colleague has created a PR to fix this issue: https://github.com/Wootric/WootricSDK-Android/pull/89
Can you check and let us know if the solution works for you?

Thanks!

**Comment by diegoserranoa** [comment]
Hi @prasannarupan we've released a new version fixing this issue. Can you try and let us know? 🙏 thanks!
https://github.com/Wootric/WootricSDK-Android/releases/tag/2.17.0

**Comment by prasannarupan** [comment]
@diegoserranoa  this issue is fixed. verified in the latest SDK
