### ISSUE TITLE
When using FragmentActivity, onSurveyDidShow() cannot be call back

### ISSUE THREAD

**Issue by breakwhile** [Wootric/WootricSDK-Android#91]
**Summary**
When we use wootric.init(FragmentActivity fragmentActivity, String clientId, String accountToken) for initialization, the onSurveyDidShow callback cannot be triggered

**Wootric version**
2.16.0

**root cause**
In the SurveyManager.showSurveyFragment() method, this code is missing in the first if code block:

`
if (currentEvent.getSurveyCallback() != null){
                    currentEvent.getSurveyCallback().onSurveyDidShow();
 }
`

Why is there this code when using Activity? Is this logic by design?
![1596621884367](https://user-images.githubusercontent.com/15830036/89400214-2bc16a80-d746-11ea-897e-c7ebd061214d.jpg)
![1596621528002](https://user-images.githubusercontent.com/15830036/89399823-96be7180-d745-11ea-9969-5c17b91746ac.jpg)

**Comment by diegoserranoa** [comment]
Hi @breakwhile thanks for reporting this. I've replicated the issue and will push the fix in the next release which should come in the next few weeks with another feature. I'll mention this issue in the PR.
