### ISSUE TITLE
The stop() method will cause survey to never be displayed

### ISSUE THREAD

**Issue by breakwhile** [Wootric/WootricSDK-Android#93]
**Summary**
In the branch of ds-add-stop-method, you provide the api wootric.stop().
When we call the stop() method for the first time, it can prevent the survey() from displaying, which is correct.
However, when we call wootric.survey() again, even if we do not call the stop() method, the user is eligible for survey will not see surver()

**Branch**
https://github.com/Wootric/WootricSDK-Android/tree/ds-add-stop-method

**root cause**
The SurveyManager.runSurvey() method relies on the surveyRunning flag. When we call the stop() method, the surveyRunning flag is not set to false.
![1598515049061](https://user-images.githubusercontent.com/15830036/91413679-0f64a980-e87e-11ea-9d6b-cfcc2ad48351.jpg)

If I set surveyRunning to false in SurveyManager.stop(), it will work.
![1598515125343](https://user-images.githubusercontent.com/15830036/91413903-594d8f80-e87e-11ea-9c66-2a17856c763b.jpg)

**Comment by diegoserranoa** [comment]
Hi @breakwhile , thanks for the contribution. You're right. I tested the solution and pushed the change to that branch.
