### ISSUE TITLE
Leak Canary memory leak on logout

### ISSUE THREAD

**Issue by astamato** [Wootric/WootricSDK-Android#97]
Hi there :)

I'm an Android engineer at HubSpot. Very similarly to the explanation in [this](https://github.com/Wootric/WootricSDK-Android/pull/96) PR, we are using the Wootric SDK in our Android app, together with Leak Canary library, which has reported a memory leak in your SDK.

From our end, the leak is reproduced every time we logout from the app. Basically the host activity (HomeActivity) is destroyed and the Wootric instance is destroyed with it leaking what appears to be `currentEvent` in `SurveyManager`. 

When `survey()` is called a [WootricEvent is created](https://github.com/Wootric/WootricSDK-Android/blob/master/androidsdk/src/main/java/com/wootric/androidsdk/SurveyManager.java#L121), which in turn keeps a strong reference to the caller activity. This WootricEvent is then [kept on a global variable](https://github.com/Wootric/WootricSDK-Android/blob/master/androidsdk/src/main/java/com/wootric/androidsdk/SurveyManager.java#L158) in the SurveyManager singleton and never removed.
Removing the `!eventQueue.isEmpty()` [here](https://github.com/Wootric/WootricSDK-Android/blob/master/androidsdk/src/main/java/com/wootric/androidsdk/SurveyManager.java#L156) would fix the leak for most cases but it could still leak in case some of the requests started by the SurveyValidator failed.

The heap analysis results is in the following gist: [link](https://gist.github.com/astamato/d3f0a99cf48d6c2190c1eb912fefd3a5).

Version of Wootric: **2.17.0**

Hopefully this makes sense. Happy to answer any further questions.
Thanks a million for the help :)

**Comment by diegoserranoa** [comment]
Hi @astamato 

Thanks for reporting this issue. I'm taking a look at the PR and testing the proposed solution there. I'm testing the different scenarios to see be sure the change doesn't affect other parts of the SDK. I'll let you know once I have an update.

**Comment by Yannshu** [comment]
Hey @diegoserranoa!
To me, it sounds like the memory leak reported by @astamato is a different one than the one fixed in my [PR](https://github.com/Wootric/WootricSDK-Android/pull/96). The leak in the PR is fragment related, this one is activity related.
This leak doesn't show up when using the Wootric sample app with Leak Canary, as it's a single activity app (and so is the app I'm working on at Deliveroo).
From the description, I'm pretty sure this leak can easily be reproduced by displaying the survey in one activity, and then navigating to another activity.
That's just my two cents on this :)

**Comment by astamato** [comment]
Hey! Yes, it is indeed a different memory leak, I've added some details as to what we believe the issue is and what may fix it. 

The reason I quoted the other PR is because we found it in the same way by using Leak Canary, sorry for the confusion and thanks @Yannshu for your comment :)

**Comment by diegoserranoa** [comment]
Hi @astamato  , I've created a new [PR](https://github.com/Wootric/WootricSDK-Android/pull/99) merging the two solutions and also added a fix for another leak I was able to find. Can you please test and let me know if it's working correctly for you? 🙏 

Thanks!

**Comment by astamato** [comment]
@diegoserranoa great stuff, tested 2.18.1 and leak is gone :D
